# Generated by Django 3.0.6 on 2020-06-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20200605_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='question',
            field=models.TextField(),
        ),
    ]
