# Generated by Django 3.0.6 on 2020-06-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20200609_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
