# Generated by Django 3.0.6 on 2020-06-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_deck_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='mastered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
