# Generated by Django 3.0.6 on 2020-06-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20200610_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='mastered',
        ),
    ]
