# Generated by Django 3.0.6 on 2020-06-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_remove_card_mastered'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='mastered',
            field=models.BooleanField(default=False),
        ),
    ]
