# Generated by Django 3.0.6 on 2020-06-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_auto_20200610_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='mastered',
            field=models.BooleanField(default=False, verbose_name='Mastered'),
        ),
    ]
